---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  product_name: chef
  product_version: 13.1.31

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[ngix::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes: